services:
  grafana:
    depends_on:
      - mosquitto
    build: grafana/.
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - grafana/config/.env
    environment:
      - GF_INSTALL_PLUGINS=grafana-mqtt-datasource,orchestracities-map-panel
    volumes:
      - ./grafana/config/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-storage:/var/lib/grafana
    networks:
      - thalamus-network
    restart: always

  mosquitto:
    build: mosquitto/.
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - thalamus-network
    restart: always

  portainer:
    build: portainer/.
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - thalamus-network
    restart: always

networks:
  thalamus-network:
    name: thalamus-network
    driver: bridge

volumes:
  grafana-storage:
    name: thalamus-grafana-storage
  portainer_data:
    name: thalamus-portainer-data
  mosquitto-data:
    name: thalamus-mosquitto-data
  mosquitto-log:
    name: thalamus-mosquitto-log
