apiVersion: 1

datasources:
  - name: thalamus-mqtt
    type: grafana-mqtt-datasource
    uid: eeyb2q9aigd1cb
    access: proxy
    jsonData:
      uri: "tcp://mosquitto:1883"
      username: "${MQTT_USERNAME}"
    secureJsonData:
      password: "${MQTT_PASSWORD}"
